/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cassel.nosql;

public class App
{
    public String getGreeting()
    {
        return "Hello world.";
    }
    
    public static void main(String[] args) throws Exception
    {
        System.out.println(new App().getGreeting());
        
        FirebaseConnection dbManager = new FirebaseConnection();
        UserInteractions ui = new UserInteractions(dbManager);
        
        ui.run();
    }

}
